services:
  # API Services
  studentservice.api:
    image: studentservice.api
    build:
      context: .
      dockerfile: Services/StudentService/StudentService.API/Dockerfile
    ports:
      - "7002:80"
    depends_on:
      - postgres
      - redis
      - rabbitmq
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - STUDENT_SERVICE_DB=${STUDENT_SERVICE_DB}
      - REDIS_CACHE_CONNECTION=${REDIS_CACHE_CONNECTION}
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_USERNAME=${RABBITMQ_USERNAME}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
    networks:
      - edusmartai-network

  authservice.api:
    image: authservice.api
    build:
      context: .
      dockerfile: Services/AuthService/AuthService.API/Dockerfile
    ports:
      - "7001:80"
    depends_on:
      - postgres
      - redis
      - rabbitmq
    environment:
      - AUTH_SERVICE_DB=${AUTH_SERVICE_DB}
      - REDIS_CACHE_CONNECTION=${REDIS_CACHE_CONNECTION}
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_USERNAME=${RABBITMQ_USERNAME}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - JWT_AUDIENCE=${JWT_AUDIENCE}
      - CLIENT_ID=${CLIENT_ID}
      - CLIENT_SECRET=${CLIENT_SECRET}
    networks:
      - edusmartai-network

  # Gateway
  reverseproxy:
    image: reverseproxy
    build:
      context: .
      dockerfile: Gateways/ReverseProxy/Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - studentservice.api
      - authservice.api
    environment:
      - AUTH_SERVICE_URL=${AUTH_SERVICE_URL}
      - STUDENT_SERVICE_URL=${STUDENT_SERVICE_URL}
      - CLIENT_ID=${CLIENT_ID}
      - CLIENT_SECRET=${CLIENT_SECRET}
      - JWT_AUDIENCE=${JWT_AUDIENCE}
    networks:
      - edusmartai-network

# Networks
networks:
  edusmartai-network:
    driver: bridge

# Volumes
volumes:
  postgres_data:
  redis_data:
  rabbitmq_data: