global using BaseService.Application.Interfaces.IdentityHepers;
global using BaseService.Application.Interfaces.Repositories;
global using BaseService.Common.Utils.Const;
global using BuildingBlocks.Pagination;
global using Course.Application.Interfaces;
global using Course.Application.Interfaces.Helpers.Courses;
global using Course.Domain.Models;
global using FluentValidation;
global using MassTransit;
global using Microsoft.EntityFrameworkCore;
global using StackExchange.Redis;
global using System.Linq.Expressions;
global using CourseEntity = Course.Domain.Models.Course;
