// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace StudentService.Domain.WriteModels;

public partial class AiEvaluationImprovement
{
    public Guid ImprovementId { get; set; }

    public Guid EvaluationId { get; set; }

    public int PositionIndex { get; set; }

    public string ImprovementsText { get; set; }

    public string ContentMarkdown { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public string Slug { get; set; }

    public virtual AiEvaluation Evaluation { get; set; }
}