// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using BaseService.Infrastructure.Contexts;
using Course.Domain.Models;
using Microsoft.EntityFrameworkCore;

namespace Course.Infrastructure.Data;

public partial class CourseDbContext : AppDbContext
{
    public CourseDbContext(DbContextOptions<CourseDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<CourseEntity> Courses { get; set; }

    public virtual DbSet<CourseAudience> CourseAudiences { get; set; }

    public virtual DbSet<CourseComment> CourseComments { get; set; }

    public virtual DbSet<CourseObjective> CourseObjectives { get; set; }

    public virtual DbSet<CourseRating> CourseRatings { get; set; }

    public virtual DbSet<CourseRecommendation> CourseRecommendations { get; set; }

    public virtual DbSet<CourseRequirement> CourseRequirements { get; set; }

    public virtual DbSet<CourseStudentEnrollment> CourseStudentEnrollments { get; set; }

    public virtual DbSet<CourseTag> CourseTags { get; set; }

    public virtual DbSet<Lesson> Lessons { get; set; }

    public virtual DbSet<LessonQuiz> LessonQuizzes { get; set; }

    public virtual DbSet<LessonTranscript> LessonTranscripts { get; set; }

    public virtual DbSet<Major> Majors { get; set; }

    public virtual DbSet<Module> Modules { get; set; }

    public virtual DbSet<ModuleDiscussion> ModuleDiscussions { get; set; }

    public virtual DbSet<ModuleMaterial> ModuleMaterials { get; set; }

    public virtual DbSet<ModuleObjective> ModuleObjectives { get; set; }

    public virtual DbSet<ModuleQuiz> ModuleQuizzes { get; set; }

    public virtual DbSet<Note> Notes { get; set; }

    public virtual DbSet<Semester> Semesters { get; set; }

    public virtual DbSet<Subject> Subjects { get; set; }

    public virtual DbSet<Syllabus> Syllabi { get; set; }

    public virtual DbSet<SyllabusSemester> SyllabusSemesters { get; set; }

    public virtual DbSet<SyllabusSubject> SyllabusSubjects { get; set; }

    public virtual DbSet<Tag> Tags { get; set; }

    public virtual DbSet<UserCourseProgress> UserCourseProgresses { get; set; }

    public virtual DbSet<UserLessonProgress> UserLessonProgresses { get; set; }

    public virtual DbSet<UserModuleProgress> UserModuleProgresses { get; set; }

    public virtual DbSet<VUserCourseProgress> VUserCourseProgresses { get; set; }

    public virtual DbSet<VUserModuleProgress> VUserModuleProgresses { get; set; }
    public virtual DbSet<VMajorSemesterSubjectCourses> VMajorSemesterSubjectCoursess { get; set; }
	public virtual DbSet<VwCourseInfo> VwCourseInfos { get; set; }

	protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder
            .HasPostgresEnum("course_status", new[] { "draft", "published", "archived" })
            .HasPostgresExtension("pgcrypto")
            .HasPostgresExtension("vector");

        modelBuilder.Entity<CourseEntity>(entity =>
        {
            entity.HasKey(e => e.CourseId).HasName("courses_pkey");

            entity.ToTable("courses");

            entity.HasIndex(e => e.IsActive, "idx_courses_is_active");

            entity.HasIndex(e => e.SubjectId, "idx_courses_subject");

            entity.HasIndex(e => e.TeacherId, "idx_courses_teacher");

            entity.HasIndex(e => e.Slug, "uq_courses_slug").IsUnique();

            entity.Property(e => e.CourseId)
                .HasDefaultValueSql("gen_random_uuid()")
                .HasColumnName("course_id");
            entity.Property(e => e.CourseImageUrl).HasColumnName("course_image_url");
            entity.Property(e => e.CourseIntroVideoUrl).HasColumnName("course_intro_video_url");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnName("created_at");
            entity.Property(e => e.CreatedBy)
                .HasMaxLength(100)
                .HasColumnName("created_by");
            entity.Property(e => e.DealPrice)
                .HasPrecision(10, 2)
                .HasColumnName("deal_price");
            entity.Property(e => e.Description).HasColumnName("description");
            entity.Property(e => e.DurationHours)
                .HasPrecision(8, 2)
                .HasComputedColumnSql("round(((COALESCE(duration_minutes, 0))::numeric / 60.0), 2)", true)
                .HasColumnName("duration_hours");
            entity.Property(e => e.DurationMinutes).HasColumnName("duration_minutes");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasColumnName("is_active");
            entity.Property(e => e.LearnerCount)
                .HasDefaultValue(0)
                .HasColumnName("learner_count");
            entity.Property(e => e.Level).HasColumnName("level");
            entity.Property(e => e.Price)
                .HasPrecision(10, 2)
                .HasColumnName("price");
            entity.Property(e => e.ShortDescription)
                .HasMaxLength(300)
                .HasColumnName("short_description");
            entity.Property(e => e.Slug)
                .HasMaxLength(160)
                .HasColumnName("slug");
            entity.Property(e => e.SubjectId).HasColumnName("subject_id");
            entity.Property(e => e.TeacherId).HasColumnName("teacher_id");
            entity.Property(e => e.Title)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("title");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnName("updated_at");
            entity.Property(e => e.UpdatedBy)
                .HasMaxLength(100)
                .HasColumnName("updated_by");

            entity.HasOne(d => d.Subject).WithMany(p => p.Courses)
                .HasForeignKey(d => d.SubjectId)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("fk_courses_subject");
        });

        modelBuilder.Entity<CourseAudience>(entity =>
        {
            entity.HasKey(e => e.AudienceId).HasName("course_audiences_pkey");

            entity.ToTable("course_audiences");

            entity.HasIndex(e => e.CourseId, "idx_course_audiences_course");

            entity.HasIndex(e => new { e.CourseId, e.PositionIndex }, "uq_course_audiences_course_pos_active")
                .IsUnique()
                .HasFilter("(is_active = true)");

            entity.Property(e => e.AudienceId)
                .HasDefaultValueSql("gen_random_uuid()")
                .HasColumnName("audience_id");
            entity.Property(e => e.Content)
                .IsRequired()
                .HasColumnName("content");
            entity.Property(e => e.CourseId).HasColumnName("course_id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnName("created_at");
            entity.Property(e => e.CreatedBy)
                .HasMaxLength(100)
                .HasColumnName("created_by");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasColumnName("is_active");
            entity.Property(e => e.PositionIndex)
                .HasDefaultValue(0)
                .HasColumnName("position_index");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnName("updated_at");
            entity.Property(e => e.UpdatedBy)
                .HasMaxLength(100)
                .HasColumnName("updated_by");

            entity.HasOne(d => d.Course).WithMany(p => p.CourseAudiences)
                .HasForeignKey(d => d.CourseId)
                .HasConstraintName("course_audiences_course_id_fkey");
        });

        modelBuilder.Entity<CourseComment>(entity =>
        {
            entity.HasKey(e => e.CommentId).HasName("course_comments_pkey");

            entity.ToTable("course_comments");

            entity.HasIndex(e => e.CourseId, "idx_comments_course");

            entity.HasIndex(e => e.IsActive, "idx_comments_is_active");

            entity.HasIndex(e => e.ParentCommentId, "idx_comments_parent");

            entity.Property(e => e.CommentId)
                .HasDefaultValueSql("gen_random_uuid()")
                .HasColumnName("comment_id");
            entity.Property(e => e.Content)
                .IsRequired()
                .HasColumnName("content");
            entity.Property(e => e.CourseId).HasColumnName("course_id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnName("created_at");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasColumnName("is_active");
            entity.Property(e => e.ParentCommentId).HasColumnName("parent_comment_id");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnName("updated_at");
            entity.Property(e => e.UserId).HasColumnName("user_id");

            entity.HasOne(d => d.Course).WithMany(p => p.CourseComments)
                .HasForeignKey(d => d.CourseId)
                .HasConstraintName("fk_comments_course");

            entity.HasOne(d => d.ParentComment).WithMany(p => p.InverseParentComment)
                .HasForeignKey(d => d.ParentCommentId)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("fk_comments_parent");
        });

        modelBuilder.Entity<CourseObjective>(entity =>
        {
            entity.HasKey(e => e.ObjectiveId).HasName("course_objectives_pkey");

            entity.ToTable("course_objectives");

            entity.HasIndex(e => e.CourseId, "idx_course_objectives_course");

            entity.HasIndex(e => new { e.CourseId, e.PositionIndex }, "uq_course_objectives_course_pos")
                .IsUnique()
                .HasFilter("(is_active = true)");

            entity.Property(e => e.ObjectiveId)
                .HasDefaultValueSql("gen_random_uuid()")
                .HasColumnName("objective_id");
            entity.Property(e => e.Content)
                .IsRequired()
                .HasColumnName("content");
            entity.Property(e => e.CourseId).HasColumnName("course_id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnName("created_at");
            entity.Property(e => e.CreatedBy)
                .HasMaxLength(100)
                .HasColumnName("created_by");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasColumnName("is_active");
            entity.Property(e => e.PositionIndex)
                .HasDefaultValue(0)
                .HasColumnName("position_index");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnName("updated_at");
            entity.Property(e => e.UpdatedBy)
                .HasMaxLength(100)
                .HasColumnName("updated_by");

            entity.HasOne(d => d.Course).WithMany(p => p.CourseObjectives)
                .HasForeignKey(d => d.CourseId)
                .HasConstraintName("course_objectives_course_id_fkey");
        });

        modelBuilder.Entity<CourseRating>(entity =>
        {
            entity.HasKey(e => e.RatingId).HasName("course_ratings_pkey");

            entity.ToTable("course_ratings");

            entity.HasIndex(e => e.IsActive, "idx_course_ratings_is_active");

            entity.HasIndex(e => e.CourseId, "idx_ratings_course");

            entity.HasIndex(e => e.UserId, "idx_ratings_user");

            entity.HasIndex(e => new { e.CourseId, e.UserId }, "uq_ratings_course_user").IsUnique();

            entity.Property(e => e.RatingId)
                .HasDefaultValueSql("gen_random_uuid()")
                .HasColumnName("rating_id");
            entity.Property(e => e.CourseId).HasColumnName("course_id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnName("created_at");
            entity.Property(e => e.CreatedBy)
                .HasMaxLength(100)
                .HasColumnName("created_by");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasColumnName("is_active");
            entity.Property(e => e.Rating).HasColumnName("rating");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnName("updated_at");
            entity.Property(e => e.UpdatedBy)
                .HasMaxLength(100)
                .HasColumnName("updated_by");
            entity.Property(e => e.UserId).HasColumnName("user_id");

            entity.HasOne(d => d.Course).WithMany(p => p.CourseRatings)
                .HasForeignKey(d => d.CourseId)
                .HasConstraintName("fk_ratings_course");
        });

        modelBuilder.Entity<CourseRecommendation>(entity =>
        {
            entity.HasKey(e => e.RecommendationId).HasName("course_recommendations_pkey");

            entity.ToTable("course_recommendations");

            entity.HasIndex(e => e.CourseId, "idx_reco_course");

            entity.HasIndex(e => e.UserId, "idx_reco_user");

            entity.HasIndex(e => new { e.UserId, e.CourseId, e.AlgoVersion }, "uq_reco_user_course_algo").IsUnique();

            entity.Property(e => e.RecommendationId)
                .HasDefaultValueSql("gen_random_uuid()")
                .HasColumnName("recommendation_id");
            entity.Property(e => e.AlgoVersion)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("algo_version");
            entity.Property(e => e.CourseId).HasColumnName("course_id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnName("created_at");
            entity.Property(e => e.ReasonJson)
                .HasColumnType("jsonb")
                .HasColumnName("reason_json");
            entity.Property(e => e.Score)
                .HasPrecision(6, 4)
                .HasColumnName("score");
            entity.Property(e => e.UserId).HasColumnName("user_id");

            entity.HasOne(d => d.Course).WithMany(p => p.CourseRecommendations)
                .HasForeignKey(d => d.CourseId)
                .HasConstraintName("fk_reco_course");
        });

        modelBuilder.Entity<CourseRequirement>(entity =>
        {
            entity.HasKey(e => e.RequirementId).HasName("course_requirements_pkey");

            entity.ToTable("course_requirements");

            entity.HasIndex(e => e.CourseId, "idx_course_requirements_course");

            entity.HasIndex(e => new { e.CourseId, e.PositionIndex }, "uq_course_requirements_course_pos")
                .IsUnique()
                .HasFilter("(is_active = true)");

            entity.Property(e => e.RequirementId)
                .HasDefaultValueSql("gen_random_uuid()")
                .HasColumnName("requirement_id");
            entity.Property(e => e.Content)
                .IsRequired()
                .HasColumnName("content");
            entity.Property(e => e.CourseId).HasColumnName("course_id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnName("created_at");
            entity.Property(e => e.CreatedBy)
                .HasMaxLength(100)
                .HasColumnName("created_by");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasColumnName("is_active");
            entity.Property(e => e.PositionIndex)
                .HasDefaultValue(0)
                .HasColumnName("position_index");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnName("updated_at");
            entity.Property(e => e.UpdatedBy)
                .HasMaxLength(100)
                .HasColumnName("updated_by");

            entity.HasOne(d => d.Course).WithMany(p => p.CourseRequirements)
                .HasForeignKey(d => d.CourseId)
                .HasConstraintName("course_requirements_course_id_fkey");
        });

        modelBuilder.Entity<CourseStudentEnrollment>(entity =>
        {
            entity.HasKey(e => e.EnrollmentId).HasName("course_student_enrollments_pkey");

            entity.ToTable("course_student_enrollments");

            entity.HasIndex(e => e.CourseId, "idx_cse_course");

            entity.HasIndex(e => e.UserId, "idx_cse_user");

            entity.HasIndex(e => new { e.CourseId, e.UserId }, "idx_enroll_active").HasFilter("is_active");

            entity.HasIndex(e => new { e.UserId, e.CourseId }, "uq_cse_user_course_active")
                .IsUnique()
                .HasFilter("(is_active = true)");

            entity.Property(e => e.EnrollmentId)
                .HasDefaultValueSql("gen_random_uuid()")
                .HasColumnName("enrollment_id");
            entity.Property(e => e.CourseId).HasColumnName("course_id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnName("created_at");
            entity.Property(e => e.CreatedBy)
                .HasMaxLength(100)
                .HasColumnName("created_by");
            entity.Property(e => e.ExpiresAt).HasColumnName("expires_at");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasColumnName("is_active");
            entity.Property(e => e.StartedAt)
                .HasDefaultValueSql("now()")
                .HasColumnName("started_at");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnName("updated_at");
            entity.Property(e => e.UpdatedBy)
                .HasMaxLength(100)
                .HasColumnName("updated_by");
            entity.Property(e => e.UserId).HasColumnName("user_id");

            entity.HasOne(d => d.Course).WithMany(p => p.CourseStudentEnrollments)
                .HasForeignKey(d => d.CourseId)
                .HasConstraintName("fk_cse_course");
        });

        modelBuilder.Entity<CourseTag>(entity =>
        {
            entity.HasKey(e => new { e.CourseId, e.TagId }).HasName("course_tags_pkey");

            entity.ToTable("course_tags");

            entity.HasIndex(e => e.IsActive, "idx_course_tags_is_active");

            entity.HasIndex(e => e.TagId, "idx_course_tags_tag");

            entity.Property(e => e.CourseId).HasColumnName("course_id");
            entity.Property(e => e.TagId).HasColumnName("tag_id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnName("created_at");
            entity.Property(e => e.CreatedBy)
                .HasMaxLength(100)
                .HasColumnName("created_by");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasColumnName("is_active");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnName("updated_at");
            entity.Property(e => e.UpdatedBy)
                .HasMaxLength(100)
                .HasColumnName("updated_by");

            entity.HasOne(d => d.Course).WithMany(p => p.CourseTags)
                .HasForeignKey(d => d.CourseId)
                .HasConstraintName("fk_course_tags_course");

            entity.HasOne(d => d.Tag).WithMany(p => p.CourseTags)
                .HasForeignKey(d => d.TagId)
                .HasConstraintName("fk_course_tags_tag");
        });

        modelBuilder.Entity<Lesson>(entity =>
        {
            entity.HasKey(e => e.LessonId).HasName("lessons_pkey");

            entity.ToTable("lessons");

            entity.HasIndex(e => e.IsActive, "idx_lessons_is_active");

            entity.HasIndex(e => e.ModuleId, "idx_lessons_module");

            entity.HasIndex(e => e.ModuleId, "idx_lessons_module_active").HasFilter("is_active");

            entity.HasIndex(e => new { e.ModuleId, e.PositionIndex }, "uq_lessons_module_position_active")
                .IsUnique()
                .HasFilter("(is_active = true)");

            entity.Property(e => e.LessonId)
                .HasDefaultValueSql("gen_random_uuid()")
                .HasColumnName("lesson_id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnName("created_at");
            entity.Property(e => e.CreatedBy)
                .HasMaxLength(100)
                .HasColumnName("created_by");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasColumnName("is_active");
            entity.Property(e => e.ModuleId).HasColumnName("module_id");
            entity.Property(e => e.PositionIndex).HasColumnName("position_index");
            entity.Property(e => e.Title)
                .IsRequired()
                .HasMaxLength(200)
                .HasColumnName("title");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnName("updated_at");
            entity.Property(e => e.UpdatedBy)
                .HasMaxLength(100)
                .HasColumnName("updated_by");
            entity.Property(e => e.VideoDurationSec).HasColumnName("video_duration_sec");
            entity.Property(e => e.VideoUrl).HasColumnName("video_url");

            entity.HasOne(d => d.Module).WithMany(p => p.Lessons)
                .HasForeignKey(d => d.ModuleId)
                .HasConstraintName("fk_lessons_module");
        });

        modelBuilder.Entity<LessonQuiz>(entity =>
        {
            entity.HasKey(e => e.LessonId).HasName("lesson_quizzes_pkey");

            entity.ToTable("lesson_quizzes");

            entity.HasIndex(e => e.IsActive, "idx_lesson_quizzes_is_active");

            entity.HasIndex(e => e.QuizId, "uq_lesson_quizzes_quiz").IsUnique();

            entity.Property(e => e.LessonId)
                .ValueGeneratedNever()
                .HasColumnName("lesson_id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnName("created_at");
            entity.Property(e => e.CreatedBy)
                .HasMaxLength(100)
                .HasColumnName("created_by");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasColumnName("is_active");
            entity.Property(e => e.QuizId).HasColumnName("quiz_id");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnName("updated_at");
            entity.Property(e => e.UpdatedBy)
                .HasMaxLength(100)
                .HasColumnName("updated_by");

            entity.HasOne(d => d.Lesson).WithOne(p => p.LessonQuiz)
                .HasForeignKey<LessonQuiz>(d => d.LessonId)
                .HasConstraintName("fk_lesson_quizzes_lesson");
        });

        modelBuilder.Entity<LessonTranscript>(entity =>
        {
            entity.HasKey(e => e.TranscriptId).HasName("lesson_transcripts_pkey");

            entity.ToTable("lesson_transcripts");

            entity.HasIndex(e => e.LessonId, "idx_lesson_transcripts_lesson");

            entity.HasIndex(e => e.Status, "idx_lesson_transcripts_status");

            entity.HasIndex(e => new { e.LessonId, e.Language }, "uq_lesson_transcripts_active")
                .IsUnique()
                .HasFilter("(is_active = true)");

            entity.Property(e => e.TranscriptId)
                .HasDefaultValueSql("gen_random_uuid()")
                .HasColumnName("transcript_id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnName("created_at");
            entity.Property(e => e.Error).HasColumnName("error");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasColumnName("is_active");
            entity.Property(e => e.Language)
                .HasMaxLength(16)
                .HasColumnName("language");
            entity.Property(e => e.LessonId).HasColumnName("lesson_id");
            entity.Property(e => e.Status)
                .HasDefaultValue((short)0)
                .HasColumnName("status");
            entity.Property(e => e.TextFull).HasColumnName("text_full");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnName("updated_at");
            entity.Property(e => e.VttPublicId).HasColumnName("vtt_public_id");
            entity.Property(e => e.VttUrl).HasColumnName("vtt_url");

            entity.HasOne(d => d.Lesson).WithMany(p => p.LessonTranscripts)
                .HasForeignKey(d => d.LessonId)
                .HasConstraintName("lesson_transcripts_lesson_id_fkey");
        });

		modelBuilder.Entity<Major>(entity =>
		{
			entity.HasKey(e => e.MajorId).HasName("majors_pkey");

			entity.ToTable("majors");

			entity.HasIndex(e => e.CreatedBy, "idx_majors_created_by");

			entity.HasIndex(e => e.ParentMajorId, "idx_majors_parent");

			entity.HasIndex(e => e.UpdatedBy, "idx_majors_updated_by");

			entity.HasIndex(e => e.MajorCode, "majors_major_code_key").IsUnique();

			entity.Property(e => e.MajorId)
				.HasDefaultValueSql("gen_random_uuid()")
				.HasColumnName("major_id");
			entity.Property(e => e.CreatedAt)
				.HasDefaultValueSql("now()")
				.HasColumnName("created_at");
			entity.Property(e => e.CreatedBy)
				.HasMaxLength(100)
				.HasColumnName("created_by");
			entity.Property(e => e.Description).HasColumnName("description");
			entity.Property(e => e.IsActive)
				.HasDefaultValue(true)
				.HasColumnName("is_active");
			entity.Property(e => e.MajorCode)
				.IsRequired()
				.HasMaxLength(15)
				.HasColumnName("major_code");
			entity.Property(e => e.MajorName)
				.IsRequired()
				.HasMaxLength(150)
				.HasColumnName("major_name");
			entity.Property(e => e.ParentMajorId).HasColumnName("parent_major_id");
			entity.Property(e => e.UpdatedAt)
				.HasDefaultValueSql("now()")
				.HasColumnName("updated_at");
			entity.Property(e => e.UpdatedBy)
				.HasMaxLength(100)
				.HasColumnName("updated_by");

			entity.HasOne(d => d.ParentMajor).WithMany(p => p.InverseParentMajor)
				.HasForeignKey(d => d.ParentMajorId)
				.OnDelete(DeleteBehavior.SetNull)
				.HasConstraintName("fk_majors_parent");
		});

		modelBuilder.Entity<Module>(entity =>
        {
            entity.HasKey(e => e.ModuleId).HasName("modules_pkey");

            entity.ToTable("modules");

            entity.HasIndex(e => e.CourseId, "idx_modules_course");

            entity.HasIndex(e => e.CourseId, "idx_modules_course_active").HasFilter("is_active");

            entity.HasIndex(e => e.IsActive, "idx_modules_is_active");

            entity.HasIndex(e => e.IsCore, "idx_modules_is_core");

            entity.HasIndex(e => new { e.CourseId, e.PositionIndex }, "uq_modules_course_position_active")
                .IsUnique()
                .HasFilter("(is_active = true)");

            entity.Property(e => e.ModuleId)
                .HasDefaultValueSql("gen_random_uuid()")
                .HasColumnName("module_id");
            entity.Property(e => e.CourseId).HasColumnName("course_id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnName("created_at");
            entity.Property(e => e.CreatedBy)
                .HasMaxLength(100)
                .HasColumnName("created_by");
            entity.Property(e => e.Description)
                .HasMaxLength(500)
                .HasColumnName("description");
            entity.Property(e => e.DurationHours)
                .HasPrecision(8, 2)
                .HasComputedColumnSql("round(((COALESCE(duration_minutes, 0))::numeric / 60.0), 2)", true)
                .HasColumnName("duration_hours");
            entity.Property(e => e.DurationMinutes).HasColumnName("duration_minutes");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasColumnName("is_active");
            entity.Property(e => e.IsCore)
                .HasDefaultValue(true)
                .HasColumnName("is_core");
            entity.Property(e => e.Level).HasColumnName("level");
            entity.Property(e => e.ModuleName)
                .IsRequired()
                .HasMaxLength(150)
                .HasColumnName("module_name");
            entity.Property(e => e.PositionIndex).HasColumnName("position_index");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnName("updated_at");
            entity.Property(e => e.UpdatedBy)
                .HasMaxLength(100)
                .HasColumnName("updated_by");

            entity.HasOne(d => d.Course).WithMany(p => p.Modules)
                .HasForeignKey(d => d.CourseId)
                .HasConstraintName("fk_modules_course");
        });

        modelBuilder.Entity<ModuleDiscussion>(entity =>
        {
            entity.HasKey(e => e.DiscussionId).HasName("module_discussions_pkey");

            entity.ToTable("module_discussions");

            entity.HasIndex(e => e.IsActive, "idx_module_discussions_is_active");

            entity.HasIndex(e => e.ModuleId, "idx_module_discussions_module");

            entity.Property(e => e.DiscussionId)
                .HasDefaultValueSql("gen_random_uuid()")
                .HasColumnName("discussion_id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnName("created_at");
            entity.Property(e => e.CreatedBy)
                .HasMaxLength(100)
                .HasColumnName("created_by");
            entity.Property(e => e.Description).HasColumnName("description");
            entity.Property(e => e.DiscussionQuestion)
                .IsRequired()
                .HasColumnName("discussion_question");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasColumnName("is_active");
            entity.Property(e => e.ModuleId).HasColumnName("module_id");
            entity.Property(e => e.Title)
                .IsRequired()
                .HasMaxLength(200)
                .HasColumnName("title");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnName("updated_at");
            entity.Property(e => e.UpdatedBy)
                .HasMaxLength(100)
                .HasColumnName("updated_by");

            entity.HasOne(d => d.Module).WithMany(p => p.ModuleDiscussions)
                .HasForeignKey(d => d.ModuleId)
                .HasConstraintName("fk_module_discussions_module");
        });

        modelBuilder.Entity<ModuleMaterial>(entity =>
        {
            entity.HasKey(e => e.MaterialId).HasName("module_materials_pkey");

            entity.ToTable("module_materials");

            entity.HasIndex(e => e.IsActive, "idx_module_materials_is_active");

            entity.HasIndex(e => e.ModuleId, "idx_module_materials_module");

            entity.Property(e => e.MaterialId)
                .HasDefaultValueSql("gen_random_uuid()")
                .HasColumnName("material_id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnName("created_at");
            entity.Property(e => e.CreatedBy)
                .HasMaxLength(100)
                .HasColumnName("created_by");
            entity.Property(e => e.Description).HasColumnName("description");
            entity.Property(e => e.FileUrl).HasColumnName("file_url");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasColumnName("is_active");
            entity.Property(e => e.ModuleId).HasColumnName("module_id");
            entity.Property(e => e.Title)
                .IsRequired()
                .HasMaxLength(200)
                .HasColumnName("title");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnName("updated_at");
            entity.Property(e => e.UpdatedBy)
                .HasMaxLength(100)
                .HasColumnName("updated_by");

            entity.HasOne(d => d.Module).WithMany(p => p.ModuleMaterials)
                .HasForeignKey(d => d.ModuleId)
                .HasConstraintName("fk_module_materials_module");
        });

        modelBuilder.Entity<ModuleObjective>(entity =>
        {
            entity.HasKey(e => e.ObjectiveId).HasName("module_objectives_pkey");

            entity.ToTable("module_objectives");

            entity.HasIndex(e => e.ModuleId, "idx_module_objectives_module");

            entity.HasIndex(e => new { e.ModuleId, e.PositionIndex }, "uq_module_objectives_module_pos")
                .IsUnique()
                .HasFilter("(is_active = true)");

            entity.Property(e => e.ObjectiveId)
                .HasDefaultValueSql("gen_random_uuid()")
                .HasColumnName("objective_id");
            entity.Property(e => e.Content)
                .IsRequired()
                .HasColumnName("content");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnName("created_at");
            entity.Property(e => e.CreatedBy)
                .HasMaxLength(100)
                .HasColumnName("created_by");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasColumnName("is_active");
            entity.Property(e => e.ModuleId).HasColumnName("module_id");
            entity.Property(e => e.PositionIndex)
                .HasDefaultValue(0)
                .HasColumnName("position_index");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnName("updated_at");
            entity.Property(e => e.UpdatedBy)
                .HasMaxLength(100)
                .HasColumnName("updated_by");

            entity.HasOne(d => d.Module).WithMany(p => p.ModuleObjectives)
                .HasForeignKey(d => d.ModuleId)
                .HasConstraintName("module_objectives_module_id_fkey");
        });

        modelBuilder.Entity<ModuleQuiz>(entity =>
        {
            entity.HasKey(e => e.ModuleId).HasName("module_quizzes_pkey");

            entity.ToTable("module_quizzes");

            entity.HasIndex(e => e.IsActive, "idx_module_quizzes_is_active");

            entity.HasIndex(e => e.QuizId, "uq_module_quizzes_quiz").IsUnique();

            entity.Property(e => e.ModuleId)
                .ValueGeneratedNever()
                .HasColumnName("module_id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnName("created_at");
            entity.Property(e => e.CreatedBy)
                .HasMaxLength(100)
                .HasColumnName("created_by");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasColumnName("is_active");
            entity.Property(e => e.QuizId).HasColumnName("quiz_id");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnName("updated_at");
            entity.Property(e => e.UpdatedBy)
                .HasMaxLength(100)
                .HasColumnName("updated_by");

            entity.HasOne(d => d.Module).WithOne(p => p.ModuleQuiz)
                .HasForeignKey<ModuleQuiz>(d => d.ModuleId)
                .HasConstraintName("fk_module_quizzes_module");
        });

        modelBuilder.Entity<Note>(entity =>
        {
            entity.HasKey(e => e.NoteId).HasName("notes_pkey");

            entity.ToTable("notes");

            entity.HasIndex(e => e.IsDeleted, "idx_notes_is_deleted");

            entity.HasIndex(e => e.LessonId, "idx_notes_lesson");

            entity.HasIndex(e => e.UserId, "idx_notes_user");

            entity.Property(e => e.NoteId)
                .HasDefaultValueSql("gen_random_uuid()")
                .HasColumnName("note_id");
            entity.Property(e => e.Content)
                .IsRequired()
                .HasColumnName("content");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnName("created_at");
            entity.Property(e => e.IsDeleted)
                .HasDefaultValue(false)
                .HasColumnName("is_deleted");
            entity.Property(e => e.LessonId).HasColumnName("lesson_id");
            entity.Property(e => e.TimeSeconds).HasColumnName("time_seconds");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnName("updated_at");
            entity.Property(e => e.UserId).HasColumnName("user_id");

            entity.HasOne(d => d.Lesson).WithMany(p => p.Notes)
                .HasForeignKey(d => d.LessonId)
                .HasConstraintName("fk_notes_lesson");
        });

        modelBuilder.Entity<Semester>(entity =>
        {
            entity.HasKey(e => e.SemesterId).HasName("semesters_pkey");

            entity.ToTable("semesters");

            entity.HasIndex(e => e.SemesterCode, "semesters_semester_code_key").IsUnique();

            entity.Property(e => e.SemesterId)
                .HasDefaultValueSql("gen_random_uuid()")
                .HasColumnName("semester_id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnName("created_at");
            entity.Property(e => e.SemesterNumber)
                .HasColumnName("semester_number");
            entity.Property(e => e.SemesterCode)
                .IsRequired()
                .HasMaxLength(10)
                .HasColumnName("semester_code");
            entity.Property(e => e.SemesterName)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("semester_name");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnName("updated_at");
        });

        modelBuilder.Entity<Subject>(entity =>
        {
            entity.HasKey(e => e.SubjectId).HasName("subjects_pkey");

            entity.ToTable("subjects");

            entity.HasIndex(e => e.SubjectCode, "subjects_subject_code_key").IsUnique();

            entity.Property(e => e.SubjectId)
                .HasDefaultValueSql("gen_random_uuid()")
                .HasColumnName("subject_id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnName("created_at");
            entity.Property(e => e.CreatedBy)
                .HasMaxLength(100)
                .HasColumnName("created_by");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasColumnName("is_active");
            entity.Property(e => e.SubjectCode)
                .IsRequired()
                .HasMaxLength(15)
                .HasColumnName("subject_code");
            entity.Property(e => e.SubjectName)
                .IsRequired()
                .HasMaxLength(200)
                .HasColumnName("subject_name");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnName("updated_at");
            entity.Property(e => e.UpdatedBy)
                .HasMaxLength(100)
                .HasColumnName("updated_by");

            entity.HasMany(d => d.PrereqSubjects).WithMany(p => p.Subjects)
                .UsingEntity<Dictionary<string, object>>(
                    "SubjectPrerequisite",
                    r => r.HasOne<Subject>().WithMany()
                        .HasForeignKey("PrereqSubjectId")
                        .HasConstraintName("fk_subject_prereq_prereq"),
                    l => l.HasOne<Subject>().WithMany()
                        .HasForeignKey("SubjectId")
                        .HasConstraintName("fk_subject_prereq_subject"),
                    j =>
                    {
                        j.HasKey("SubjectId", "PrereqSubjectId").HasName("subject_prerequisites_pkey");
                        j.ToTable("subject_prerequisites");
                        j.IndexerProperty<Guid>("SubjectId").HasColumnName("subject_id");
                        j.IndexerProperty<Guid>("PrereqSubjectId").HasColumnName("prereq_subject_id");
                    });

            entity.HasMany(d => d.Subjects).WithMany(p => p.PrereqSubjects)
                .UsingEntity<Dictionary<string, object>>(
                    "SubjectPrerequisite",
                    r => r.HasOne<Subject>().WithMany()
                        .HasForeignKey("SubjectId")
                        .HasConstraintName("fk_subject_prereq_subject"),
                    l => l.HasOne<Subject>().WithMany()
                        .HasForeignKey("PrereqSubjectId")
                        .HasConstraintName("fk_subject_prereq_prereq"),
                    j =>
                    {
                        j.HasKey("SubjectId", "PrereqSubjectId").HasName("subject_prerequisites_pkey");
                        j.ToTable("subject_prerequisites");
                        j.IndexerProperty<Guid>("SubjectId").HasColumnName("subject_id");
                        j.IndexerProperty<Guid>("PrereqSubjectId").HasColumnName("prereq_subject_id");
                    });
        });

		modelBuilder.Entity<Syllabus>(entity =>
		{
			entity.HasKey(e => e.SyllabusId).HasName("syllabus_pkey");

			entity.ToTable("syllabus");

			entity.HasIndex(e => e.IsActive, "idx_syllabus_active");

			entity.HasIndex(e => e.CreatedBy, "idx_syllabus_created_by");

			entity.HasIndex(e => e.MajorId, "idx_syllabus_major");

			entity.HasIndex(e => e.UpdatedBy, "idx_syllabus_updated_by");

			entity.HasIndex(e => new { e.MajorId, e.VersionLabel }, "uq_syllabus_major_version").IsUnique();

			entity.Property(e => e.SyllabusId)
				.HasDefaultValueSql("gen_random_uuid()")
				.HasColumnName("syllabus_id");
			entity.Property(e => e.CreatedAt)
				.HasDefaultValueSql("now()")
				.HasColumnName("created_at");
			entity.Property(e => e.CreatedBy)
				.HasMaxLength(100)
				.HasColumnName("created_by");
			entity.Property(e => e.EffectiveFrom).HasColumnName("effective_from");
			entity.Property(e => e.EffectiveTo).HasColumnName("effective_to");
			entity.Property(e => e.IsActive)
				.HasDefaultValue(true)
				.HasColumnName("is_active");
			entity.Property(e => e.MajorId).HasColumnName("major_id");
			entity.Property(e => e.UpdatedAt)
				.HasDefaultValueSql("now()")
				.HasColumnName("updated_at");
			entity.Property(e => e.UpdatedBy)
				.HasMaxLength(100)
				.HasColumnName("updated_by");
			entity.Property(e => e.VersionLabel)
				.IsRequired()
				.HasMaxLength(30)
				.HasColumnName("version_label");

			entity.HasOne(d => d.Major).WithMany(p => p.Syllabi)
				.HasForeignKey(d => d.MajorId)
				.OnDelete(DeleteBehavior.Restrict)
				.HasConstraintName("fk_syllabus_major");
		});

		modelBuilder.Entity<SyllabusSemester>(entity =>
        {
            entity.HasKey(e => new { e.SyllabusId, e.SemesterId }).HasName("syllabus_semesters_pkey");

            entity.ToTable("syllabus_semesters");

            entity.HasIndex(e => new { e.SyllabusId, e.PositionIndex }, "uq_ss_order").IsUnique();

            entity.Property(e => e.SyllabusId).HasColumnName("syllabus_id");
            entity.Property(e => e.SemesterId).HasColumnName("semester_id");
            entity.Property(e => e.PositionIndex).HasColumnName("position_index");

            entity.HasOne(d => d.Semester).WithMany(p => p.SyllabusSemesters)
                .HasForeignKey(d => d.SemesterId)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("fk_ss_semester");

            entity.HasOne(d => d.Syllabus).WithMany(p => p.SyllabusSemesters)
                .HasForeignKey(d => d.SyllabusId)
                .HasConstraintName("fk_ss_syllabus");
        });

        modelBuilder.Entity<SyllabusSubject>(entity =>
        {
            entity.HasKey(e => new { e.SyllabusId, e.SemesterId, e.SubjectId }).HasName("syllabus_subjects_pkey");

            entity.ToTable("syllabus_subjects");

            entity.HasIndex(e => e.SemesterId, "idx_sls_semester");

            entity.HasIndex(e => e.SubjectId, "idx_sls_subject");

            entity.Property(e => e.SyllabusId).HasColumnName("syllabus_id");
            entity.Property(e => e.SemesterId).HasColumnName("semester_id");
            entity.Property(e => e.SubjectId).HasColumnName("subject_id");
            entity.Property(e => e.Credit).HasColumnName("credit");
            entity.Property(e => e.IsMandatory)
                .HasDefaultValue(true)
                .HasColumnName("is_mandatory");
            entity.Property(e => e.PositionIndex)
                .HasDefaultValue(1)
                .HasColumnName("position_index");

            entity.HasOne(d => d.Semester).WithMany(p => p.SyllabusSubjects)
                .HasForeignKey(d => d.SemesterId)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("fk_sls_semester");

            entity.HasOne(d => d.Subject).WithMany(p => p.SyllabusSubjects)
                .HasForeignKey(d => d.SubjectId)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("fk_sls_subject");

            entity.HasOne(d => d.Syllabus).WithMany(p => p.SyllabusSubjects)
                .HasForeignKey(d => d.SyllabusId)
                .HasConstraintName("fk_sls_syllabus");
        });

        modelBuilder.Entity<Tag>(entity =>
        {
            entity.HasKey(e => e.TagId).HasName("tags_pkey");

            entity.ToTable("tags");

            entity.HasIndex(e => e.TagName, "tags_tag_name_key").IsUnique();

            entity.Property(e => e.TagId).HasColumnName("tag_id");
            entity.Property(e => e.TagName)
                .IsRequired()
                .HasMaxLength(30)
                .HasColumnName("tag_name");
        });

        modelBuilder.Entity<UserCourseProgress>(entity =>
        {
            entity.HasKey(e => e.UserCourseProgressId).HasName("user_course_progress_pkey");

            entity.ToTable("user_course_progress");

            entity.HasIndex(e => e.CourseId, "idx_ucp_course");

            entity.HasIndex(e => e.UserId, "idx_ucp_user");

            entity.HasIndex(e => new { e.UserId, e.CourseId }, "uq_user_course").IsUnique();

            entity.Property(e => e.UserCourseProgressId)
                .HasDefaultValueSql("gen_random_uuid()")
                .HasColumnName("user_course_progress_id");
            entity.Property(e => e.CompletedAt).HasColumnName("completed_at");
            entity.Property(e => e.CourseId).HasColumnName("course_id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnName("created_at");
            entity.Property(e => e.LessonsCompleted)
                .HasDefaultValue(0)
                .HasColumnName("lessons_completed");
            entity.Property(e => e.LessonsTotal)
                .HasDefaultValue(0)
                .HasColumnName("lessons_total");
            entity.Property(e => e.PercentCompleted)
                .HasPrecision(5, 2)
                .HasComputedColumnSql("\nCASE\n    WHEN (lessons_total = 0) THEN (0)::numeric\n    ELSE round((((lessons_completed)::numeric * 100.0) / (lessons_total)::numeric), 2)\nEND", true)
                .HasColumnName("percent_completed");
            entity.Property(e => e.StartedAt).HasColumnName("started_at");
            entity.Property(e => e.Status)
                .HasDefaultValue((short)0)
                .HasColumnName("status");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnName("updated_at");
            entity.Property(e => e.UserId).HasColumnName("user_id");

            entity.HasOne(d => d.Course).WithMany(p => p.UserCourseProgresses)
                .HasForeignKey(d => d.CourseId)
                .HasConstraintName("user_course_progress_course_id_fkey");
        });

        modelBuilder.Entity<UserLessonProgress>(entity =>
        {
            entity.HasKey(e => e.UserLessonProgressId).HasName("user_lesson_progress_pkey");

            entity.ToTable("user_lesson_progress");

            entity.HasIndex(e => e.LessonId, "idx_progress_lesson");

            entity.HasIndex(e => e.UserId, "idx_progress_user");

            entity.HasIndex(e => new { e.UserId, e.LessonId }, "idx_ulp_user_lesson");

            entity.HasIndex(e => new { e.UserId, e.LessonId }, "uq_progress_user_lesson").IsUnique();

            entity.Property(e => e.UserLessonProgressId)
                .HasDefaultValueSql("gen_random_uuid()")
                .HasColumnName("user_lesson_progress_id");
            entity.Property(e => e.CompletedAt).HasColumnName("completed_at");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnName("created_at");
            entity.Property(e => e.DurationWatchedSec)
                .HasDefaultValue(0)
                .HasColumnName("duration_watched_sec");
            entity.Property(e => e.LastPositionSec)
                .HasDefaultValue(0)
                .HasColumnName("last_position_sec");
            entity.Property(e => e.LastSeenPositionSec)
                .HasDefaultValue(0)
                .HasColumnName("last_seen_position_sec");
            entity.Property(e => e.LessonId).HasColumnName("lesson_id");
            entity.Property(e => e.Status).HasColumnName("status");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnName("updated_at");
            entity.Property(e => e.UserId).HasColumnName("user_id");

            entity.HasOne(d => d.Lesson).WithMany(p => p.UserLessonProgresses)
                .HasForeignKey(d => d.LessonId)
                .HasConstraintName("fk_progress_lesson");
        });

        modelBuilder.Entity<UserModuleProgress>(entity =>
        {
            entity.HasKey(e => e.UserModuleProgressId).HasName("user_module_progress_pkey");

            entity.ToTable("user_module_progress");

            entity.HasIndex(e => e.ModuleId, "idx_ump_module");

            entity.HasIndex(e => e.UserId, "idx_ump_user");

            entity.HasIndex(e => new { e.UserId, e.ModuleId }, "uq_user_module").IsUnique();

            entity.Property(e => e.UserModuleProgressId)
                .HasDefaultValueSql("gen_random_uuid()")
                .HasColumnName("user_module_progress_id");
            entity.Property(e => e.CompletedAt).HasColumnName("completed_at");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnName("created_at");
            entity.Property(e => e.LessonsCompleted)
                .HasDefaultValue(0)
                .HasColumnName("lessons_completed");
            entity.Property(e => e.LessonsTotal)
                .HasDefaultValue(0)
                .HasColumnName("lessons_total");
            entity.Property(e => e.ModuleId).HasColumnName("module_id");
            entity.Property(e => e.PercentCompleted)
                .HasPrecision(5, 2)
                .HasComputedColumnSql("\nCASE\n    WHEN (lessons_total = 0) THEN (0)::numeric\n    ELSE round((((lessons_completed)::numeric * 100.0) / (lessons_total)::numeric), 2)\nEND", true)
                .HasColumnName("percent_completed");
            entity.Property(e => e.StartedAt).HasColumnName("started_at");
            entity.Property(e => e.Status)
                .HasDefaultValue((short)0)
                .HasColumnName("status");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnName("updated_at");
            entity.Property(e => e.UserId).HasColumnName("user_id");

            entity.HasOne(d => d.Module).WithMany(p => p.UserModuleProgresses)
                .HasForeignKey(d => d.ModuleId)
                .HasConstraintName("user_module_progress_module_id_fkey");
        });

        modelBuilder.Entity<VUserCourseProgress>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("v_user_course_progress");

            entity.Property(e => e.CourseId).HasColumnName("course_id");
            entity.Property(e => e.LessonsCompleted).HasColumnName("lessons_completed");
            entity.Property(e => e.LessonsTotal).HasColumnName("lessons_total");
            entity.Property(e => e.PercentCompleted).HasColumnName("percent_completed");
            entity.Property(e => e.UserId).HasColumnName("user_id");
        });

        modelBuilder.Entity<VUserModuleProgress>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("v_user_module_progress");

            entity.Property(e => e.LessonsCompleted).HasColumnName("lessons_completed");
            entity.Property(e => e.LessonsTotal).HasColumnName("lessons_total");
            entity.Property(e => e.ModuleId).HasColumnName("module_id");
            entity.Property(e => e.PercentCompleted).HasColumnName("percent_completed");
            entity.Property(e => e.UserId).HasColumnName("user_id");
        });
        modelBuilder.Entity<VMajorSemesterSubjectCourses>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("v_major_semester_subject_courses");

            entity.Property(e => e.MajorCode).HasColumnName("major_code");
            entity.Property(e => e.SemesterNumber).HasColumnName("semester_number");
            entity.Property(e => e.SemesterCode).HasColumnName("semester_code");
            entity.Property(e => e.SemesterName).HasColumnName("semester_name");
            entity.Property(e => e.SubjectCode).HasColumnName("subject_code");
            entity.Property(e => e.SubjectName).HasColumnName("subject_name");

            entity.Property(e => e.CourseId).HasColumnName("course_id");
            entity.Property(e => e.CourseTitle).HasColumnName("course_title");
            entity.Property(e => e.Level).HasColumnName("level");

            entity.Property(e => e.Price)
                .HasPrecision(10, 2)
                .HasColumnName("price");
            entity.Property(e => e.DealPrice)
                .HasPrecision(10, 2)
                .HasColumnName("deal_price");

            entity.Property(e => e.DurationMinutes).HasColumnName("duration_minutes");
            entity.Property(e => e.Slug).HasColumnName("slug");
            entity.Property(e => e.CourseImageUrl).HasColumnName("course_image_url");
            entity.Property(e => e.LearnerCount).HasColumnName("learner_count");
            entity.Property(e => e.IsActive).HasColumnName("is_active");

            entity.Property(e => e.DurationHours)
                .HasPrecision(8, 2)
                .HasColumnName("duration_hours");
            entity.Property(e => e.Description).HasColumnName("description");
            entity.Property(e => e.ShortDescription).HasColumnName("short_description");
        });

		modelBuilder.Entity<VwCourseInfo>(entity =>
		{
			entity
				.HasNoKey()
				.ToView("vw_course_info");

			entity.Property(e => e.CourseId).HasColumnName("course_id");
			entity.Property(e => e.Description).HasColumnName("description");
			entity.Property(e => e.DurationHours)
				.HasPrecision(8, 2)
				.HasColumnName("duration_hours");
			entity.Property(e => e.DurationMinutes).HasColumnName("duration_minutes");
			entity.Property(e => e.IsCore).HasColumnName("is_core");
			entity.Property(e => e.LearnerCount).HasColumnName("learner_count");
			entity.Property(e => e.LessonId).HasColumnName("lesson_id");
			entity.Property(e => e.LessonTitle)
				.HasMaxLength(200)
				.HasColumnName("lesson_title");
			entity.Property(e => e.Level).HasColumnName("level");
			entity.Property(e => e.MaterialFileUrl).HasColumnName("material_file_url");
			entity.Property(e => e.MaterialId).HasColumnName("material_id");
			entity.Property(e => e.MaterialTitle)
				.HasMaxLength(200)
				.HasColumnName("material_title");
			entity.Property(e => e.ModuleId).HasColumnName("module_id");
			entity.Property(e => e.ModuleName)
				.HasMaxLength(150)
				.HasColumnName("module_name");
			entity.Property(e => e.TeacherId).HasColumnName("teacher_id");
			entity.Property(e => e.TranscriptId).HasColumnName("transcript_id");
			entity.Property(e => e.TranscriptLanguage)
				.HasMaxLength(16)
				.HasColumnName("transcript_language");
			entity.Property(e => e.TranscriptText).HasColumnName("transcript_text");
			entity.Property(e => e.VideoDurationSec).HasColumnName("video_duration_sec");
			entity.Property(e => e.VideoUrl).HasColumnName("video_url");
		});

		OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}
