// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Course.Domain.Models;

public partial class CourseTag
{
    public Guid CourseId { get; set; }

    public long TagId { get; set; }

    public DateTime CreatedAt { get; set; }

    public bool IsActive { get; set; }

    public string CreatedBy { get; set; }

    public string UpdatedBy { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual Course Course { get; set; }

    public virtual Tag Tag { get; set; }
}