// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Course.Domain.Models;

public partial class LessonTranscript
{
    public Guid TranscriptId { get; set; }

    public Guid LessonId { get; set; }

    public string Language { get; set; }

    public short Status { get; set; }

    public string TextFull { get; set; }

    public string Error { get; set; }

    public string VttUrl { get; set; }

    public string VttPublicId { get; set; }

    public bool IsActive { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual Lesson Lesson { get; set; }
}