// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Course.Domain.Models;

public partial class ModuleMaterial
{
    public Guid MaterialId { get; set; }

    public Guid ModuleId { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public string FileUrl { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public string CreatedBy { get; set; }

    public string UpdatedBy { get; set; }

    public bool IsActive { get; set; }

    public virtual Module Module { get; set; }
}