// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Course.Domain.Models;

public partial class ModuleDiscussionComment
{
    public Guid CommentId { get; set; }

    public Guid DiscussionId { get; set; }

    public Guid? ParentCommentId { get; set; }

    public Guid UserId { get; set; }

    public string UserDisplayName { get; set; }

    public string Content { get; set; }

    public bool IsActive { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public string CreatedBy { get; set; }

    public string UpdatedBy { get; set; }

    public virtual ModuleDiscussion Discussion { get; set; }

    public virtual ICollection<ModuleDiscussionComment> InverseParentComment { get; set; } = new List<ModuleDiscussionComment>();

    public virtual ModuleDiscussionComment ParentComment { get; set; }
}