// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Course.Domain.Models;

public partial class Module
{
    public Guid ModuleId { get; set; }

    public Guid CourseId { get; set; }

    public string ModuleName { get; set; }

    public int PositionIndex { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public string CreatedBy { get; set; }

    public string UpdatedBy { get; set; }

    public bool IsActive { get; set; }

    public int? DurationMinutes { get; set; }

    public decimal? DurationHours { get; set; }

    public short? Level { get; set; }

    public bool IsCore { get; set; }

    public virtual Course Course { get; set; }

    public virtual ICollection<Lesson> Lessons { get; set; } = new List<Lesson>();

    public virtual ICollection<ModuleObjective> ModuleObjectives { get; set; } = new List<ModuleObjective>();
}