// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Course.Domain.Models;

public partial class UserModuleProgress
{
    public Guid UserModuleProgressId { get; set; }

    public Guid UserId { get; set; }

    public Guid ModuleId { get; set; }

    public int LessonsTotal { get; set; }

    public int LessonsCompleted { get; set; }

    public decimal? PercentCompleted { get; set; }

    public short Status { get; set; }

    public DateTime? StartedAt { get; set; }

    public DateTime? CompletedAt { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual Module Module { get; set; }
}