// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Course.Domain.Models;

// v_major_semester_subject_prereqs
public partial class VMajorSemesterSubjectPrereqs
{
    public string MajorCode { get; set; }

    public short SemesterIndex { get; set; }

    public int SubjectIndex { get; set; }

    public string SubjectCode { get; set; }

    public string SubjectName { get; set; }

    public List<string> PrereqSubjectCodes { get; set; }
}

