// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Course.Domain.Models;
// v_major_semester_subject_courses
public partial class VMajorSemesterSubjectCourses
{
    public string MajorCode { get; set; }
    public short SemesterNumber { get; set; }
    public string SemesterCode { get; set; }
    public string SemesterName { get; set; }
    public string SubjectCode { get; set; }
    public string SubjectName { get; set; }
    public Guid? CourseId { get; set; }
    public string CourseTitle { get; set; }
    public short? Level { get; set; }
    public decimal? Price { get; set; }
    public decimal? DealPrice { get; set; }
    public int? DurationMinutes { get; set; }
    public string Slug { get; set; }
    public string CourseImageUrl { get; set; }
    public int? LearnerCount { get; set; }
    public bool? IsActive { get; set; }
    public decimal? DurationHours { get; set; }
    public string Description { get; set; }
    public string ShortDescription { get; set; }
}