// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Course.Domain.Models;

public partial class VUserModuleProgress
{
    public Guid? UserId { get; set; }

    public Guid? ModuleId { get; set; }

    public long? LessonsTotal { get; set; }

    public long? LessonsCompleted { get; set; }

    public decimal? PercentCompleted { get; set; }
}