// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Course.Domain.Models;

public partial class VwCourseInfo
{
    public Guid? CourseId { get; set; }

    public Guid? TeacherId { get; set; }

    public int? DurationMinutes { get; set; }

    public decimal? DurationHours { get; set; }

    public string Description { get; set; }

    public int? LearnerCount { get; set; }

    public short? Level { get; set; }

    public Guid? ModuleId { get; set; }

    public string ModuleName { get; set; }

    public bool? IsCore { get; set; }

    public Guid? LessonId { get; set; }

    public string LessonTitle { get; set; }

    public int? VideoDurationSec { get; set; }

    public string VideoUrl { get; set; }

    public Guid? MaterialId { get; set; }

    public string MaterialTitle { get; set; }

    public string MaterialFileUrl { get; set; }

    public Guid? TranscriptId { get; set; }

    public string TranscriptLanguage { get; set; }

    public string TranscriptText { get; set; }
}