// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Course.Domain.Models;

public partial class VwOverviewCourseProgress
{
    public Guid? UserCourseProgressId { get; set; }

    public Guid? UserId { get; set; }

    public Guid? CourseId { get; set; }

    public int? LessonsTotal { get; set; }

    public int? LessonsCompleted { get; set; }

    public decimal? PercentCompleted { get; set; }

    public short? Status { get; set; }

    public DateTime? StartedAt { get; set; }

    public DateTime? CompletedAt { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public short? Level { get; set; }

    public int? DurationMinutes { get; set; }

    public decimal? DurationHours { get; set; }

    public Guid? TeacherId { get; set; }

    public string Title { get; set; }

    public int? LearnerCount { get; set; }

    public long? TotalDurationWatchedSec { get; set; }

    public long? TotalModuleQuizzes { get; set; }

    public long? TotalLessonQuizzes { get; set; }

    public string LessonProgressList { get; set; }
}