// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Course.Domain.Models;

public partial class VwSubjectDependency
{
    public string SubjectCode { get; set; }

    public string SubjectName { get; set; }

    public string PrereqSubjectCode { get; set; }

    public string PrereqSubjectName { get; set; }

    public string SubjectMajorCode { get; set; }

    public string PrereqMajorCode { get; set; }

    public int? SemesterIndex { get; set; }

    public short? SemesterNumber { get; set; }
}