// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PaymentService.Domain.Models;

public partial class CartItem
{
    public Guid CartItemId { get; set; }

    public Guid CartId { get; set; }

    public Guid CourseId { get; set; }

    public string CourseTitleSnapshot { get; set; }

    public string CourseImageUrlSnapshot { get; set; }

    public decimal PriceSnapshot { get; set; }

    public decimal? DealPriceSnapshot { get; set; }

    public bool IsSelected { get; set; }

    public short Status { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public string CreatedBy { get; set; }

    public string UpdatedBy { get; set; }

    public virtual Cart Cart { get; set; }
}