// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PaymentService.Domain.Models;

public partial class PaymentTransaction
{
    public Guid PaymentId { get; set; }

    public Guid OrderId { get; set; }

    public string Gateway { get; set; }

    public string GatewayTransactionId { get; set; }

    public decimal Amount { get; set; }

    public string Currency { get; set; }

    public short Status { get; set; }

    public string ReturnCode { get; set; }

    public string ReturnMessage { get; set; }

    public string RawResponse { get; set; }

    public string ClientIp { get; set; }

    public string UserAgent { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual Order Order { get; set; }
}